using Grpc.Core;
using Spiceport.Core;
using Spiceport.Datastore;
using Spiceport.Grains;
using V1 = Authzed.Api.V1;
using CoreUpdateOperation = Spiceport.Core.UpdateOperation;

namespace Spiceport.Api;

/// <summary>
/// gRPC front door for the <c>authzed.api.v1.WatchService</c>. Server-streaming Watch tails the
/// silo-singleton <see cref="IDatastore.Watch"/> directly (a long-lived stream is a poor fit for a
/// request/response grain). Each emitted <see cref="V1::WatchResponse"/> carries its own ZedToken
/// (<c>changes_through</c>) so a client can resume exactly once after a disconnect. v1 deltas vs the
/// internal Watch: filter emitted updates by <c>optional_object_types</c>; no <c>schema_updated</c> field
/// (this snapshot watches relationships only).
/// </summary>
public sealed class AuthzedWatchV1Service(IDatastore datastore, ISchemaProvider schemaProvider)
    : V1::WatchService.WatchServiceBase
{
    public override async Task Watch(
        V1::WatchRequest request,
        IServerStreamWriter<V1::WatchResponse> responseStream,
        ServerCallContext context)
    {
        ArgumentNullException.ThrowIfNull(request);

        var cancellationToken = context.CancellationToken;

        // Empty => no filter; otherwise emit only updates whose resource object type is in the set.
        var objectTypeFilter = request.OptionalObjectTypes.Count == 0
            ? null
            : new HashSet<string>(request.OptionalObjectTypes);

        // Resolve the start cursor: a supplied token decodes to its revision (rejecting a mismatched
        // datastore); otherwise start from current head so only future writes are tailed.
        IRevision afterRevision;
        if (request.OptionalStartCursor is { Token.Length: > 0 } cursor)
        {
            var parser = await datastore.GetRevisionParser(cancellationToken);
            var decoded = ZedTokens.DecodeRevision(new Core.ZedToken(cursor.Token), parser);
            if (decoded.Status == ZedTokenStatus.MismatchedDatastoreId)
                throw new RpcException(new Status(
                    StatusCode.InvalidArgument,
                    "start cursor was generated by a different datastore instance"));
            if (decoded.Status == ZedTokenStatus.Unknown)
                throw new RpcException(new Status(StatusCode.InvalidArgument, "invalid start cursor"));
            afterRevision = decoded.Revision;
        }
        else
        {
            var head = await datastore.HeadRevision(cancellationToken);
            afterRevision = head.Revision;
        }

        var datastoreId = await datastore.GetUniqueId(cancellationToken);
        var options = new WatchOptions(ResolveContent(request));

        // The datastore Watch is a lazy iterator: cursor-validity and watch-enablement checks throw on
        // the first MoveNextAsync, not at GetAsyncEnumerator, so the catch must wrap the iteration.
        var enumerator = datastore.Watch(afterRevision, options, cancellationToken).GetAsyncEnumerator(cancellationToken);
        try
        {
            while (true)
            {
                bool moved;
                try
                {
                    moved = await enumerator.MoveNextAsync();
                }
                catch (OperationCanceledException)
                {
                    break;
                }
                catch (RevisionNotFoundException ex)
                {
                    // The cursor is older than the retained GC window — cannot replay from it.
                    throw new RpcException(new Status(StatusCode.FailedPrecondition, ex.Message));
                }
                catch (WatchDisabledException ex)
                {
                    // The backend cannot support Watch (e.g. Postgres without track_commit_timestamp=on).
                    throw new RpcException(new Status(StatusCode.FailedPrecondition, ex.Message));
                }

                if (!moved)
                    break;

                if (cancellationToken.IsCancellationRequested)
                    break;

                var change = enumerator.Current;
                var response = ToResponse(change, datastoreId, objectTypeFilter);

                // Checkpoints always flow through (they carry revision-progress liveness for filtered
                // consumers). Otherwise skip a content response whose every update was filtered out.
                if (!change.IsCheckpoint && response.Updates.Count == 0 &&
                    !change.SchemaChanged && objectTypeFilter is not null)
                {
                    continue;
                }

                await responseStream.WriteAsync(response);
            }
        }
        finally
        {
            await enumerator.DisposeAsync();
        }
    }

    private V1::WatchResponse ToResponse(
        RevisionChange change, string datastoreId, HashSet<string>? objectTypeFilter)
    {
        var token = ZedTokens.FromRevision(change.Revision, schemaProvider.Current.SchemaHash, datastoreId);
        var response = new V1::WatchResponse
        {
            ChangesThrough = new V1::ZedToken { Token = token.Token },
            SchemaUpdated = change.SchemaChanged,
            IsCheckpoint = change.IsCheckpoint,
        };

        // A checkpoint carries no content, only the revision.
        if (change.IsCheckpoint)
            return response;

        foreach (var update in change.RelationshipChanges)
        {
            if (objectTypeFilter is not null &&
                !objectTypeFilter.Contains(update.Relationship.Resource.ObjectType))
            {
                continue;
            }

            response.Updates.Add(ToProto(update));
        }

        return response;
    }

    /// <summary>
    /// Maps the request's <c>optional_update_kinds</c> to the datastore's <see cref="WatchContent"/>.
    /// An empty selector defaults to relationships only (backwards-compatible).
    /// </summary>
    private static WatchContent ResolveContent(V1::WatchRequest request)
    {
        if (request.OptionalUpdateKinds.Count == 0)
            return WatchContent.Relationships;

        WatchContent content = 0;
        foreach (var kind in request.OptionalUpdateKinds)
        {
            content |= kind switch
            {
                V1::WatchKind.IncludeSchemaUpdates => WatchContent.Schema,
                V1::WatchKind.IncludeCheckpoints => WatchContent.Checkpoints,
                _ => WatchContent.Relationships,
            };
        }

        // No additive fallback needed here: the datastore's checkpoint emission (see
        // IDatastore.Watch/WatchOptions) is keyed off commit activity itself, not off whether the
        // requested content flags matched anything, so a checkpoints-only (or schema-only) mask still
        // sees checkpoints emitted on every commit.
        return content;
    }

    private static V1::RelationshipUpdate ToProto(Core.RelationshipUpdate update)
    {
        var op = update.Operation switch
        {
            CoreUpdateOperation.Create => V1::RelationshipUpdate.Types.Operation.Create,
            CoreUpdateOperation.Delete => V1::RelationshipUpdate.Types.Operation.Delete,
            _ => V1::RelationshipUpdate.Types.Operation.Touch,
        };
        return new V1::RelationshipUpdate { Operation = op, Relationship = ToProto(update.Relationship) };
    }

    private static V1::Relationship ToProto(Core.Relationship rel)
    {
        var subjectRelation = rel.Subject.Relation == CoreConstants.Ellipsis ? string.Empty : rel.Subject.Relation;
        var proto = new V1::Relationship
        {
            Resource = new V1::ObjectReference
            {
                ObjectType = rel.Resource.ObjectType,
                ObjectId = rel.Resource.ObjectId,
            },
            Relation = rel.Resource.Relation,
            Subject = new V1::SubjectReference
            {
                Object = new V1::ObjectReference
                {
                    ObjectType = rel.Subject.ObjectType,
                    ObjectId = rel.Subject.ObjectId,
                },
                OptionalRelation = subjectRelation,
            },
        };

        if (rel.OptionalCaveat is { } caveat)
        {
            var pc = new V1::ContextualizedCaveat { CaveatName = caveat.CaveatName };
            if (DictToStruct(caveat.Context) is { } ctx)
                pc.Context = ctx;
            proto.OptionalCaveat = pc;
        }

        if (rel.OptionalExpiration is { } expiration)
            proto.OptionalExpiresAt = Google.Protobuf.WellKnownTypes.Timestamp.FromDateTimeOffset(expiration);

        return proto;
    }

    private static Google.Protobuf.WellKnownTypes.Struct? DictToStruct(IReadOnlyDictionary<string, object?>? dict)
    {
        if (dict is null || dict.Count == 0)
            return null;

        var s = new Google.Protobuf.WellKnownTypes.Struct();
        foreach (var (k, v) in dict)
            s.Fields[k] = ObjectToValue(v);
        return s;
    }

    private static Google.Protobuf.WellKnownTypes.Value ObjectToValue(object? o) =>
        o switch
        {
            null => Google.Protobuf.WellKnownTypes.Value.ForNull(),
            bool b => Google.Protobuf.WellKnownTypes.Value.ForBool(b),
            string str => Google.Protobuf.WellKnownTypes.Value.ForString(str),
            double d => Google.Protobuf.WellKnownTypes.Value.ForNumber(d),
            int i => Google.Protobuf.WellKnownTypes.Value.ForNumber(i),
            long l => Google.Protobuf.WellKnownTypes.Value.ForNumber(l),
            IReadOnlyDictionary<string, object?> map =>
                Google.Protobuf.WellKnownTypes.Value.ForStruct(DictToStruct(map) ?? new Google.Protobuf.WellKnownTypes.Struct()),
            System.Collections.IEnumerable list =>
                Google.Protobuf.WellKnownTypes.Value.ForList(list.Cast<object?>().Select(ObjectToValue).ToArray()),
            _ => Google.Protobuf.WellKnownTypes.Value.ForString(o.ToString() ?? string.Empty),
        };
}
