using Grpc.Core;
using Spiceport.Core;
using Spiceport.Datastore;
using Spiceport.Grains;
using Spiceport.Protos;
using CoreUpdateOperation = Spiceport.Core.UpdateOperation;
using ProtoRelationship = Spiceport.Protos.Relationship;
using ProtoRelationshipUpdate = Spiceport.Protos.RelationshipUpdate;
using ProtoObjectReference = Spiceport.Protos.ObjectReference;
using ProtoSubjectReference = Spiceport.Protos.SubjectReference;
using ProtoContextualizedCaveat = Spiceport.Protos.ContextualizedCaveat;
using ZedToken = Spiceport.Protos.ZedToken;

namespace Spiceport.Api;

/// <summary>
/// gRPC front door for the relationship + schema changefeed. Server-streaming Watch consumes the
/// silo-singleton <see cref="IDatastore.Watch"/> directly rather than going through a grain: a
/// long-lived server stream is a poor fit for a request/response (stateless-worker) grain, and the
/// datastore is already a process-wide singleton, so the gRPC method simply tails its
/// <see cref="IAsyncEnumerable{T}"/> and writes each change to the response stream. Each emitted
/// response carries its own ZedToken so a client can resume exactly once after a disconnect.
/// </summary>
public sealed class WatchGrpcService(IDatastore datastore, ISchemaProvider schemaProvider)
    : Spiceport.Protos.WatchService.WatchServiceBase
{
    public override async Task Watch(
        WatchRequest request,
        IServerStreamWriter<WatchResponse> responseStream,
        ServerCallContext context)
    {
        ArgumentNullException.ThrowIfNull(request);

        var cancellationToken = context.CancellationToken;
        var content = ResolveContent(request);

        // Resolve the start cursor: a supplied token decodes to its revision (rejecting a mismatched
        // datastore); otherwise start from current head so only future writes are tailed.
        IRevision afterRevision;
        if (request.OptionalStartCursor is { Token.Length: > 0 } cursor)
        {
            var parser = await datastore.GetRevisionParser(cancellationToken);
            var decoded = ZedTokens.DecodeRevision(new Core.ZedToken(cursor.Token), parser);
            if (decoded.Status == ZedTokenStatus.MismatchedDatastoreId)
                throw new RpcException(new Status(
                    StatusCode.InvalidArgument,
                    "start cursor was generated by a different datastore instance"));
            if (decoded.Status == ZedTokenStatus.Unknown)
                throw new RpcException(new Status(StatusCode.InvalidArgument, "invalid start cursor"));
            afterRevision = decoded.Revision;
        }
        else
        {
            var head = await datastore.HeadRevision(cancellationToken);
            afterRevision = head.Revision;
        }

        var datastoreId = await datastore.GetUniqueId(cancellationToken);
        var options = new WatchOptions(content);

        IAsyncEnumerator<RevisionChange> enumerator;
        try
        {
            enumerator = datastore.Watch(afterRevision, options, cancellationToken).GetAsyncEnumerator(cancellationToken);
        }
        catch (RevisionNotFoundException ex)
        {
            // The cursor is older than the retained GC window — cannot replay from it.
            throw new RpcException(new Status(StatusCode.FailedPrecondition, ex.Message));
        }

        try
        {
            while (true)
            {
                bool moved;
                try
                {
                    moved = await enumerator.MoveNextAsync();
                }
                catch (OperationCanceledException)
                {
                    break;
                }

                if (!moved)
                    break;

                if (cancellationToken.IsCancellationRequested)
                    break;

                var change = enumerator.Current;
                // Per-write cancellation is not supported by the base IServerStreamWriter; the loop and
                // the enumerator's MoveNextAsync already observe the call's cancellation token.
                await responseStream.WriteAsync(ToResponse(change, datastoreId));
            }
        }
        finally
        {
            await enumerator.DisposeAsync();
        }
    }

    private static WatchContent ResolveContent(WatchRequest request)
    {
        if (request.OptionalUpdateKinds.Count == 0)
            return WatchContent.Relationships;

        WatchContent content = 0;
        foreach (var kind in request.OptionalUpdateKinds)
        {
            content |= kind switch
            {
                WatchKind.IncludeSchemaUpdates => WatchContent.Schema,
                _ => WatchContent.Relationships,
            };
        }
        return content;
    }

    private WatchResponse ToResponse(RevisionChange change, string datastoreId)
    {
        var token = ZedTokens.FromRevision(change.Revision, schemaProvider.Current.SchemaHash, datastoreId);
        var response = new WatchResponse
        {
            ChangesThrough = new ZedToken { Token = token.Token },
            SchemaUpdated = change.SchemaChanged,
        };

        foreach (var update in change.RelationshipChanges)
            response.Updates.Add(ToProto(update));

        return response;
    }

    private static ProtoRelationshipUpdate ToProto(Core.RelationshipUpdate update)
    {
        var op = update.Operation switch
        {
            CoreUpdateOperation.Create => ProtoRelationshipUpdate.Types.Operation.Create,
            CoreUpdateOperation.Delete => ProtoRelationshipUpdate.Types.Operation.Delete,
            _ => ProtoRelationshipUpdate.Types.Operation.Touch,
        };
        return new ProtoRelationshipUpdate { Operation = op, Relationship = ToProto(update.Relationship) };
    }

    private static ProtoRelationship ToProto(Core.Relationship rel)
    {
        var subjectRelation = rel.Subject.Relation == CoreConstants.Ellipsis ? string.Empty : rel.Subject.Relation;
        var proto = new ProtoRelationship
        {
            Resource = new ProtoObjectReference
            {
                ObjectType = rel.Resource.ObjectType,
                ObjectId = rel.Resource.ObjectId,
            },
            ResourceRelation = rel.Resource.Relation,
            Subject = new ProtoSubjectReference
            {
                Object = new ProtoObjectReference
                {
                    ObjectType = rel.Subject.ObjectType,
                    ObjectId = rel.Subject.ObjectId,
                },
                OptionalRelation = subjectRelation,
            },
            OptionalExpiresAtUnixSeconds =
                rel.OptionalExpiration is { } exp ? exp.ToUnixTimeSeconds() : 0,
        };

        if (rel.OptionalCaveat is { } caveat)
        {
            var pc = new ProtoContextualizedCaveat { CaveatName = caveat.CaveatName };
            if (DictToStruct(caveat.Context) is { } ctx)
                pc.Context = ctx;
            proto.OptionalCaveat = pc;
        }

        return proto;
    }

    private static Google.Protobuf.WellKnownTypes.Struct? DictToStruct(IReadOnlyDictionary<string, object?>? dict)
    {
        if (dict is null || dict.Count == 0)
            return null;

        var s = new Google.Protobuf.WellKnownTypes.Struct();
        foreach (var (k, v) in dict)
            s.Fields[k] = ObjectToValue(v);
        return s;
    }

    private static Google.Protobuf.WellKnownTypes.Value ObjectToValue(object? o) =>
        o switch
        {
            null => Google.Protobuf.WellKnownTypes.Value.ForNull(),
            bool b => Google.Protobuf.WellKnownTypes.Value.ForBool(b),
            string str => Google.Protobuf.WellKnownTypes.Value.ForString(str),
            double d => Google.Protobuf.WellKnownTypes.Value.ForNumber(d),
            int i => Google.Protobuf.WellKnownTypes.Value.ForNumber(i),
            long l => Google.Protobuf.WellKnownTypes.Value.ForNumber(l),
            IReadOnlyDictionary<string, object?> map =>
                Google.Protobuf.WellKnownTypes.Value.ForStruct(DictToStruct(map) ?? new Google.Protobuf.WellKnownTypes.Struct()),
            System.Collections.IEnumerable list =>
                Google.Protobuf.WellKnownTypes.Value.ForList(list.Cast<object?>().Select(ObjectToValue).ToArray()),
            _ => Google.Protobuf.WellKnownTypes.Value.ForString(o.ToString() ?? string.Empty),
        };
}
